//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyWebRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpotifyWebRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the spotify client. Retry?.
        /// </summary>
        internal static string CouldntConnectMsg {
            get {
                return ResourceManager.GetString("CouldntConnectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( 0 for Limitless ).
        /// </summary>
        internal static string MainForm_InitializeComponent___0_for_Limitless__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent___0_for_Limitless__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        internal static string MainForm_InitializeComponent__as {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Between 0-100).
        /// </summary>
        internal static string MainForm_InitializeComponent__Between_0_100_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__Between_0_100_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Record .
        /// </summary>
        internal static string MainForm_InitializeComponent__Record_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__Record_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Settings .
        /// </summary>
        internal static string MainForm_InitializeComponent__Settings_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__Settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Shuffle is on!).
        /// </summary>
        internal static string MainForm_InitializeComponent__Shuffle_is_on__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__Shuffle_is_on__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sound Quality).
        /// </summary>
        internal static string MainForm_InitializeComponent__Sound_Quality_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__Sound_Quality_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The Picture).
        /// </summary>
        internal static string MainForm_InitializeComponent__The_Picture_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent__The_Picture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainForm_InitializeComponent_About {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Art Quality:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Album_Art_Quality_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Album_Art_Quality_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MainForm_InitializeComponent_Back {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        internal static string MainForm_InitializeComponent_Clear_List {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Clear_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Version :.
        /// </summary>
        internal static string MainForm_InitializeComponent_Client_Version__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Client_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        internal static string MainForm_InitializeComponent_Delete_selected {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Delete_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate with PayPal.
        /// </summary>
        internal static string MainForm_InitializeComponent_Donate_with_PayPal {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Donate_with_PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Encoding_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Encoding_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Recordings:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Finished_Recordings_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Finished_Recordings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, check the online help.
        /// </summary>
        internal static string MainForm_InitializeComponent_For_more_information__check_the_online_help {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_For_more_information__check_the_online_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainForm_InitializeComponent_Help {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Control Panel.
        /// </summary>
        internal static string MainForm_InitializeComponent_Hide_Control_Panel {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Hide_Control_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string MainForm_InitializeComponent_Log {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 bitrate:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Mp3_bitrate_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Mp3_bitrate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally &apos;Stereo Mix&apos;. See help for more info..
        /// </summary>
        internal static string MainForm_InitializeComponent_Normally__Stereo_Mix___See_help_for_more_info_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Normally__Stereo_Mix___See_help_for_more_info_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Now_Playing_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Now_Playing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Recording:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Now_Recording_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Now_Recording_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open output folder.
        /// </summary>
        internal static string MainForm_InitializeComponent_Open_output_folder {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Open_output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rec. Devices.
        /// </summary>
        internal static string MainForm_InitializeComponent_Open_Rec__Devices {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Open_Rec__Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sound Mixer.
        /// </summary>
        internal static string MainForm_InitializeComponent_Open_Sound_Mixer {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Open_Sound_Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play selected.
        /// </summary>
        internal static string MainForm_InitializeComponent_Play_selected {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Play_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording device:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Recording_device_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Recording_device_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string MainForm_InitializeComponent_Reload {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload page.
        /// </summary>
        internal static string MainForm_InitializeComponent_Reload_page {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Reload_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save recorded mp3&apos;s in this folder:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Save_recorded_mp3_s_in_this_folder_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Save_recorded_mp3_s_in_this_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown after reaching song limit..
        /// </summary>
        internal static string MainForm_InitializeComponent_Shutdown_after_reaching_song_limit_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Shutdown_after_reaching_song_limit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Count to Save:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Song_Count_to_Save_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Song_Count_to_Save_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify Recorder.
        /// </summary>
        internal static string MainForm_InitializeComponent_Spotify_Recorder {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Spotify_Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Monitoring.
        /// </summary>
        internal static string MainForm_InitializeComponent_Start_Monitoring {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Start_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Monitoring.
        /// </summary>
        internal static string MainForm_InitializeComponent_Stop_Monitoring {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Stop_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string MainForm_InitializeComponent_Time_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Time_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version :.
        /// </summary>
        internal static string MainForm_InitializeComponent_Version__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a output folder from settings.
        /// </summary>
        internal static string MainForm_PostProccessMain_Please_set_a_output_folder_from_settings {
            get {
                return ResourceManager.GetString("MainForm_PostProccessMain_Please_set_a_output_folder_from_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be between 0-100.
        /// </summary>
        internal static string MainForm_textBoxAlbumArtQuality_TextChanged_This_value_must_be_between_0_100 {
            get {
                return ResourceManager.GetString("MainForm_textBoxAlbumArtQuality_TextChanged_This_value_must_be_between_0_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete recording....
        /// </summary>
        internal static string MainForm_toolStripMenuItem_Delete_Click_Could_not_delete_recording___ {
            get {
                return ResourceManager.GetString("MainForm_toolStripMenuItem_Delete_Click_Could_not_delete_recording___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not play song....
        /// </summary>
        internal static string MainForm_toolStripMenuItem_Play_Click_Could_not_play_song___ {
            get {
                return ResourceManager.GetString("MainForm_toolStripMenuItem_Play_Click_Could_not_play_song___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advert.
        /// </summary>
        internal static string MainForm_UpdateTrack_Advert {
            get {
                return ResourceManager.GetString("MainForm_UpdateTrack_Advert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: if you are using free version of spotify you can select CBR192 bitrate option.Higher bitrate options would be pointless for you since spotify giving 160 kbps bitrate to free users..
        /// </summary>
        internal static string NoteTxt {
            get {
                return ResourceManager.GetString("NoteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify.
        /// </summary>
        internal static string SpotifyMsgHeader {
            get {
                return ResourceManager.GetString("SpotifyMsgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify isn&apos;t running!.
        /// </summary>
        internal static string SpotifyNotRunningMsg {
            get {
                return ResourceManager.GetString("SpotifyNotRunningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpotifyWebHelper isn&apos;t running!.
        /// </summary>
        internal static string SpotifyWebHelperNotRunningMsg {
            get {
                return ResourceManager.GetString("SpotifyWebHelperNotRunningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav file couldn&apos;t be found.
        /// </summary>
        internal static string WavFileCouldNotBeFound {
            get {
                return ResourceManager.GetString("WavFileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is optimized for windows 7 or higher.
        /// </summary>
        internal static string Windows7OrLater {
            get {
                return ResourceManager.GetString("Windows7OrLater", resourceCulture);
            }
        }
    }
}
